kubectl create -f maprclusternamespace.yaml
kubectl create -f maprclusterconfigmap.yaml
kubectl create -f maprusersecrets.yaml
kubectl create -f zkservice.yaml 
kubectl create -f cldbservice.yaml
kubectl create -f zk.yaml
#kubectl create -f cldb.yaml
#kubectl create -f mfs1.yaml
#kubectl create -f mfs2.yaml
#kubectl create -f mfs3.yaml
#kubectl create -f web.yaml
