kubectl delete -f zk.yaml
kubectl delete -f cldb.yaml
kubectl delete -f mfs1.yaml
kubectl delete -f mfs2.yaml
kubectl delete -f mfs3.yaml
kubectl delete -f web.yaml
kubectl delete -f maprclusterconfigmap.yaml
kubectl delete -f maprusersecrets.yaml
kubectl delete -f zkservice.yaml 
kubectl delete -f cldbservice.yaml
kubectl delete -f maprclusternamespace.yaml
