#!/bin/bash
#MAPR_UID=5000
#MAPR_GID=5000
#MAPR_CLDB_HOSTS="cldb-0.cldb-svc.mapr-cluster.svc.cluster.local"
#MAPR_ZK_HOSTS="zk-0.zk-svc.mapr-cluster.svc.cluster.local"
#DISKARGS=12
#MAPR_CLUSTER=archerx
#MAPR_USER=mapr
#MAPR_ROOT_PASSWORD=mapr
#MAPR_PASSWORD=mapr
MAPR_BACKUP=${MAPR_BACKUP:-/tmp/backup}
MAPR_HOME=${MAPR_HOME:-/opt/mapr}
MEM_TOTAL=6291456
SECURE_CLUSTER=$NO

set_environment() {
    # Import our environment variables from systemd
    while read -r e; do
        eval "export $e"
    done <<< "$(tr "\000" "\n" < /proc/1/environ)"

    # Copy modified conf files to container
    if [ -d $MAPR_BACKUP/conf ]; then
        cp -p $MAPR_BACKUP/conf/* $MAPR_HOME/conf/
	cp -p $MAPR_BACKUP/hostid $MAPR_HOME/
    else
         echo "Conf file replacement volume not connected"
    fi
    printenv >>/tmp/init_script.log 2>&1
    echo "MAPR_USER is $MAPR_USER" >>/tmp/init_script.log 2>&1
    success $YES
}

addMapRUser() {
        groupadd -g $MAPR_GID mapr >>/tmp/init_script.log 2>&1
	useradd -u $MAPR_UID -g $MAPR_GID mapr >>/tmp/init_script.log 2>&1
}

startWarden() {
	service mapr-warden start
}

setNodeMemory()  {

        MEMTOTAL=$MAPR_MEMORY
	MEMTOTAL=`expr $MAPR_MEMORY / 1024`
        cp /proc/meminfo /opt/mapr/conf/meminfofake
        sed -i "/^MemTotal/ s/^.*$/MemTotal:     ${MEMTOTAL} kB/" /opt/mapr/conf/meminfofake
        sed -i "/^MemFree/ s/^.*$/MemFree:     ${MEMTOTAL-10} kB/" /opt/mapr/conf/meminfofake
        sed -i "/^MemAvailable/ s/^.*$/MemAvailable:     ${MEMTOTAL-10} kB/" /opt/mapr/conf/meminfofake
        sed -i ‘s!/proc/meminfo!/opt/mapr/conf/meminfofake!’ /opt/mapr/server/initscripts-common.sh
}

runConfigure() {
	if [ -f $MAPR_HOME/conf/disktab ]
	   then
	   	echo "disktab file already exist"
		/opt/mapr/server/configure.sh -C $MAPR_CLDB_HOSTS -Z $MAPR_ZK_HOSTS -N $MAPR_CLUSTER -M7 >>/tmp/init_script.log 2>&1
		startWarden		
	   else
		/opt/mapr/server/configure.sh -C $MAPR_CLDB_HOSTS -Z $MAPR_ZK_HOSTS -F /tmp/diskfile.txt -disk-opts FW$DISKARGS -N $MAPR_CLUSTER -M7 >>/tmp/init_script.log 2>&1
	fi
}

addLicense() {
        count=0;
        cd /tmp/; wget --user maprqa --password maprqa http://stage.mapr.com/license/LatestDemoLicense-M7.txt
	sleep 180;
        /opt/mapr/bin/maprcli license add -license /tmp/LatestDemoLicense-M7.txt -is_file true >>/tmp/init_script.log 2>&1
}

modifyCldbVolumeReplication() {
	maprcli volume modify -name mapr.cldb.internal -minreplication 1 -replication 2 -json
}

changePasswd() {
	echo "root:$MAPR_ROOT_PASSWORD" | chpasswd
        echo "$MAPR_USER:$MAPR_PASSWORD" | chpasswd
}

backup() {
	cp -pr /opt/mapr/conf /tmp/backup/
	cp -p /opt/mapr/hostid /tmp/backup
}
changeHostId() {
	/opt/mapr/server/mruuidgen > /opt/mapr/hostid
        cat /opt/mapr/hostid > /opt/mapr/conf/hostid.$$
}

echo "#######################################" >>/tmp/init_script.log 2>&1
echo "###########INIT SCRIPT#################" >>/tmp/init_script.log 2>&1
echo "#######################################" >>/tmp/init_script.log 2>&1
set_environment
echo $MAPR_UID >>/tmp/init_script.log 2>&1
echo $MAPR_GID >>/tmp/init_script.log 2>&1
addMapRUser
changePasswd
changeHostId
setNodeMemory
runConfigure
addLicense
modifyCldbVolumeReplication
backup
echo "Successfully setup the node" >>/tmp/init_script.log 2>&1
while true
do
sleep 5
done
