#!/bin/bash
mv /etc/systemd/system/mapr-docker.service /tmp >>/tmp/init_script.log 2>&1
cp /tmp/backup/mfs.service /etc/systemd/system/ >>/tmp/init_script.log 2>&1
cp /tmp/backup/mfs-init-script /tmp/mfs-init-script >>/tmp/init_script.log 2>&1
systemctl daemon reload
systemctl enable mfs.service
env >>/tmp/init_script.log 2>&1
exec /sbin/init
while true
do
sleep 5
done
